### ISSUE TITLE
Digitigrade legs causing Suit sprite errors (again)

### ISSUE THREAD

**Issue by TetrakoHateThis** [Skyrat-SS13/Skyrat-TG#16196]
## Testmerges:
[#15802: '[MODULAR] Fixes That Stupid Language Reset Bug That's Been Here Since Newprefs' by RimiNosha at commit 712341258d](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15802)
[#15898: 'the ash farming expands' by jjpark-kb at commit 37be60a17a](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15898)
[#15863: '[SEMI-MODULAR] A (Nearly) complete rework and rebalance of xenos' by Paxilmaniac at commit b96d897ba2](https://github.com/Skyrat-SS13/Skyrat-tg/pull/15863)
[#16068: 'Redoes bluesec clothing sprites to have a nicer, more consistent color palette, along with correcting alot of glaring mistakes.' by Ebin-Halcyon at commit e3b0803326](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16068)
[#16017: 'Reworks microfusion guns to behave like energy guns that can be upgraded, not like ballistic guns that happen to fire lasers' by Paxilmaniac at commit 523ee5e402](https://github.com/Skyrat-SS13/Skyrat-tg/pull/16017)

## Reproduction:
Take a character with digitigrade legs, put certain 'suit' items on like non-ranger ponchos, the norma hawaiian shirt or Ethereal raincoat and you'll just get the usual purple/black placeholder sprite. A number of the 'families' suit items also just plain don't appear at all when worn.

**Comment by ghost** [comment]
Already aware of it, this bug report is too broad to do anything with. If you instead give identifiers for each broken item so it can be found in the code (Name or Desc helps a lot, legit just put whatever you find into quotes for copypasting) we can look further into it.

The Families portion is fixed already. Server should have just recently updated with it.

**Comment by TetrakoHateThis** [comment]
@OrionTheFox 

**The following are still broken on Digitigrade legs and produce a placeholder sprite:**
"White Dress"
"Poncho"
"Green Poncho"
"Red Poncho"
"Ethereal Raincoat"
"Snowman Outfit"
"Hawaiian Shirt"
"Western Jacket"

**The following turn Digitigrade legs into Plantigrade:**
"TMC Coat"
"PG Coat"
"Deckers Coat"
"Soviet Coat"

**Comment by ghost** [comment]
No need for atmoization, all are caused by a single issue: digi suit icons aren't matching normal suit icons any more
Will be looked into some day soon
